name: Run Script

on:
  push:
    branches:
      - production

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Switch to main branch
        run: git checkout main

      - name: Merge changes from production
        run: git merge --no-ff production

      - name: Configure Git
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"

      - name: Push changes to main branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}
          git push --quiet --set-upstream origin main
